### PR TITLE
Code is working to analyse the runs and get efficiency (if enough chambers are there to calculate it...)

### PR DESCRIPTION
**Pull request by giovanni-mocellin**

### CODE REVIEW

**Comment by jshlee** [comment]
-1

**Comment by jshlee** [comment]
this has conflicts, overlaps with @hyunyong PR, and is way too large

**Comment by giovanni-mocellin** [comment]
Is the PR by Hyunyong merged already or not yet?
Mine derives from Hyunyong's code, from which I started to "improve" it and make it work with validation modules

**Comment by jshlee** [comment]
no its not

**Comment by jshlee** [comment]
hyunyongs version is merged.
use that

**Comment by giovanni-mocellin** [comment]
ok, i will
thanks

**Comment by jshlee** [comment]
u do know that there is a huge conflict with this PR

**Pull request closed without merging**
